spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/artgarden
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

server:
  address: 13.125.213.95
  port: 8080