#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/artgarden;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop  # 시작 시 데이터베이스 초기화
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true  # 쿼리문 가독성 있게 띄워줌
#        default_batch_fetch_size: 100
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MY_SQL_ADDRESS}
    username: ${MY_SQL_ID}
    password: ${MY_SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # 서버 시작 시 변경사항만 update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  jackson:
    time-zone: Asia/Seoul
logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
DomainURL : http://localhost:8080/