spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://artgarden.cybn84f6kzat.ap-northeast-2.rds.amazonaws.com:3306/artgarden
    username: artgarden
    password: ckdgns11
  jpa:
    hibernate:
      ddl-auto: update  # 서버 시작 시 변경사항만 update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
