spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/artgarden
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 시작 시 데이터베이스 초기화
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # 쿼리문 가독성 있게 띄워줌
        default_batch_fetch_size: 100
logging:
  level:
    org.springframework.security: TRACE